# Generated by Django 5.0.7 on 2025-09-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.CharField(max_length=32, unique=True)),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('journal', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('quality', models.CharField(max_length=10)),
                ('study_type', models.CharField(max_length=100)),
                ('sample_size', models.IntegerField(default=0)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('abstract', models.TextField(blank=True)),
            ],
        ),
    ]
