# Generated by Django 5.0.7 on 2025-11-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('keywords', models.TextField()),
                ('surgery_type', models.CharField(blank=True, max_length=100)),
                ('journal_rank', models.CharField(default='all', max_length=10)),
                ('year_from', models.IntegerField(blank=True, null=True)),
                ('year_to', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('article_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Search Cache',
                'verbose_name_plural': 'Search Caches',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='CachedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.CharField(db_index=True, max_length=32)),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('journal', models.CharField(max_length=255)),
                ('publication_date', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('abstract', models.TextField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('study_type', models.CharField(blank=True, max_length=100)),
                ('sample_size', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('quality', models.CharField(blank=True, max_length=10)),
                ('participants', models.TextField(blank=True)),
                ('outcomes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('search_cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_articles', to='search.searchcache')),
            ],
            options={
                'verbose_name': 'Cached Article',
                'verbose_name_plural': 'Cached Articles',
                'ordering': ['-year', '-publication_date'],
                'unique_together': {('search_cache', 'pmid')},
            },
        ),
    ]
