# Generated by Django 5.0.7 on 2026-02-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchcache_cachedarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
