# Generated by Django 5.0.7 on 2026-03-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_legacy_article_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedarticle',
            name='language',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
